# Dependencies
pygments:         false


# Permalinks
permalink:        pretty


# Settings
destination:      ./
exclude:          ["README.md"]
paginate_path:    "/opinar/page:num"
paginate:         4
encoding:         UTF-8
future:           false
name:             OOCN
url:              http://github.oocn.eu

collections:
 video:
  output: true
  permalink: /curtas/:path/ 
 vida:
  output: true
  permalink: /vidas/:path/
 artigos:
  output: true
  permalink: /artigos/:path/
# Links
expo_repo:        https://github.oocn.eu
expo_new_issue:   https://github.oocn.eu

docs:             http://github.oocn.eu
blog:             http://github.oocn.eu

gems:
  - jekyll-redirect-from
