# Dependencies
pygments:         false


# Permalinks
permalink:        pretty


# Settings
destination:      ./
exclude:          ["README.md"]
paginate_path:    "/opinar/page:num"
paginate:         3
encoding:         UTF-8
future:           false
name:             OOCN
url:              http://github.oocn.eu


# Links
expo_repo:        https://github.oocn.eu
expo_new_issue:   https://github.oocn.eu

docs:             http://github.oocn.eu
blog:             http://github.oocn.eu

gems:
  - jekyll-redirect-from
